POST http://localhost:3000/employee/new-employee
Content-Type: application/json

{
    "firstName": "James",
    "lastName": "Maina",
    "salary": 80000,
    "profilePic": "https://picsum.photos/721/400",
    "role": "65b3b095-8e31-4ef9-86ad-e5f08722be7f",
    "email": "jamesmaina@gmail.com",
    "password": "test12"
}

### Get all employees
GET http://localhost:3000/employee/all-employees