POST http://localhost:3000/role/new-role
Content-Type: application/json

{
    "roleName": ""
}

### Fetch all roles
GET http://localhost:3000/role/all-roles

### Delete a role by id
DELETE  http://localhost:3000/role/delete/53af4f80-19c8-40e2-bd87-08e5944bbe7f